branches:
  only: 
    - master

matrix:
  include:
    - os: linux
      language: generic
      dist: xenial
      sudo: false
      addons:
        apt:
          packages:
            - wget
            # Ubuntu needs following packages to build Swift.
            # 
            # Reference:
            # https://github.com/apple/swift#System-Requirements
            - git
            - cmake
            - ninja-build
            - clang
            - python
            - uuid-dev
            - libicu-dev
            - icu-devtools
            - libbsd-dev 
            - libedit-dev
            - libxml2-dev
            - libsqlite3-dev
            - swig
            - libpython-dev
            - libncurses5-dev
            - pkg-config
            - libblocksruntime-dev
            - libcurl4-openssl-dev
            - systemtap-sdt-dev
            - tzdata
            - rsync
      script:
        - wget https://swift.org/builds/swift-4.2-release/ubuntu1604/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu16.04.tar.gz
        - tar xvfz swift-4.2-RELEASE-ubuntu16.04.tar.gz
        - export PATH=$(pwd)/swift-4.2-RELEASE-ubuntu16.04/usr/bin:"${PATH}"
        - swift build
        - swift test
